### ISSUE TITLE
Document the reason why develop branch is the default branch

### ISSUE THREAD

**Issue by thomasyu888** [Sage-Bionetworks/challengescoring#17]
Potentially switch back to `master` so we actually have a develop branch to do release cycles.

**Comment by allaway** [comment]
Develop is the default branch so that contributors will PR against that by default, and not master. Master is for release cycles. It's the same model used in the sage synapseAnnotations repository.

**Comment by thomasyu888** [comment]
Ahh. Interesting!  I think it's fine that the develop branch is public facing / the default branch that people get when they do git clone ...

Ive always had master be the default with added branch protection so no one can push to it by accident.   We should just add documentation for people that do install the repo by source that the default is develop.

**Comment by allaway** [comment]
Yep! Ideally, we would have this in the README (not there yet, obviously): 

> To install this package, run the following R command: 
> ```
> remotes::install_github("Sage-Bionetworks/challengescoring@master")
> ```

This way people _using_ the package will get the most recent release, but people _working_ on the repo (i.e. actually cloning the repo - packages users shouldn't and won't need to do this) will be developing on the most recent changes to develop, not master.

**Comment by thomasyu888** [comment]
Renamed the issue. Thanks @allaway :)
